module.exports = {
  __init__: [
    'animation',
    'contextPads',
    //'midaContextPadProvider',
    'dataPanel',
    'disableModeling',
    'elementNotifications',
    'elementSupport',
    'exclusiveGatewaySettings',
    'inclusiveGatewaySettings',
    'keyboardBindings',
    'log',
    'midaOverlays',
    'modelSaver',
    'notifications',
    'pauseSimulation',
    'preserveElementColors',
    'processInstanceIds',
    'processInstanceSettings',
    'processInstances',
    'resetSimulation',
    'setAnimationSpeed',
    'showProcessInstance',
    'simulationState',
    'toggleMode',
    'tokenCount',
    'tokenSimulationBehavior',
    'violationsNotification',
    'tokenSimulationEditorActions',
    'tokenSimulationPalette',
    'propertiesPanel'
    ],
//'propertiesPanel': [ 'type', require('./features/data-properties-panel/lib/PropertiesPanel') ],
  'propertiesPanel': [ 'type', require('../node_modules/bpmn-js-properties-panel/lib/PropertiesPanel') ],
	'animation' : [ 'type', require('./animation/Animation') ],
	'contextPads' : [ 'type', require('./features/context-pads') ],
  //'midaContextPadProvider' : [ 'type', require('./features/mida-context-pad')],
  'dataPanel' : [ 'type', require('./features/data-panel/DataPanel') ],
	'disableModeling' : [ 'type', require('./features/disable-modeling') ],
	'elementNotifications' : [ 'type',
			require('./features/element-notifications') ],
	'elementSupport' : [ 'type', require('./features/element-support') ],
	'exclusiveGatewaySettings' : [ 'type',
			require('./features/exclusive-gateway-settings') ],
	'inclusiveGatewaySettings' : [ 'type',
			require('./features/inclusive-gateway-settings') ],
	'keyboardBindings' : [ 'type',
			require('./features/keyboard-bindings/modeler') ],
	'log' : [ 'type', require('./features/log') ],
  'midaOverlays' : [ 'type', require('./features/mida-overlays') ],
  'modelSaver' : [ 'type', require('./features/model-saver') ],
	'notifications' : [ 'type', require('./features/notifications') ],
	'pauseSimulation' : [ 'type', require('./features/pause-simulation') ],
	'preserveElementColors' : [ 'type',
			require('./features/preserve-element-colors') ],
	'processInstanceIds' : [ 'type', require('./features/process-instance-ids') ],
	'processInstanceSettings' : [ 'type',
			require('./features/process-instance-settings') ],
	'processInstances' : [ 'type', require('./features/process-instances') ],
	'resetSimulation' : [ 'type', require('./features/reset-simulation') ],
	'setAnimationSpeed' : [ 'type', require('./features/set-animation-speed') ],
	'showProcessInstance' : [ 'type',
			require('./features/show-process-instance') ],
	'simulationState' : [ 'type', require('./features/simulation-state') ],
  'showData' : [ 'type', require('./features/data-panel/ShowData') ],
	'toggleMode' : [ 'type', require('./features/toggle-mode/modeler') ],
	'tokenCount' : [ 'type', require('./features/token-count') ],
	'tokenSimulationBehavior' : [ 'type',
			require('./features/token-simulation-behavior') ],
  'violationsNotification' : [ 'type',
			require('./features/violations-notification') ],
	'tokenSimulationEditorActions' : [ 'type',
			require('./features/editor-actions') ],
	'tokenSimulationPalette' : [ 'type', require('./features/palette') ]
};
