var prefix = 'tokenSimulation';

module.exports = {
  TOGGLE_MODE_EVENT: prefix + '.toggleMode',
  GENERATE_TOKEN_EVENT: prefix + '.generateToken',
  CONSUME_TOKEN_EVENT: prefix + '.consumeToken',
  UPDATE_DATAOBJ_TYPE: prefix + '.dataObjType',
  GATEWAY_VIOLATION_EVENT: prefix + '.gatewayViolation',
  GENERATE_MESSAGE_TOKEN_EVENT: prefix + '.generateMessageToken',
  GUARD_VIOLATION_EVENT: prefix + '.guardViolation',
  CONSUME_MESSAGE_TOKEN_EVENT: prefix + '.consumeMessageToken',
  INTERMEDIATE_TOKEN_EVENT: prefix + '.intrmediateToken',
  PLAY_SIMULATION_EVENT: prefix + '.playSimulation',
  PAUSE_SIMULATION_EVENT: prefix + '.pauseSimulation',
  RESET_SIMULATION_EVENT: prefix + '.resetSimulation',
  TERMINATE_EVENT: prefix + '.terminateEvent',
  UPDATE_ELEMENTS_EVENT: prefix + '.updateElements',
  UPDATE_ELEMENT_EVENT: prefix + '.updateElement',
  UPDATE_TASK_TYPE: prefix + '.updateTaskType',
  PROCESS_INSTANCE_CREATED_EVENT: prefix + '.processInstanceCreated',
  PROCESS_INSTANCE_FINISHED_EVENT: prefix + '.processInstanceFinished',
  PROCESS_INSTANCE_SHOWN_EVENT: prefix + '.processInstanceShown',
  PROCESS_INSTANCE_HIDDEN_EVENT: prefix + '.processInstanceHidden',
  ANIMATION_CREATED_EVENT: prefix + '.animationCreated',
  DATA_UPDATE_EVENT: prefix + '.data',
  RELOAD_DIAGRAM_EVENT: prefix + '.reloadDiagram',
  SHOW_INSTANCE_DATA: prefix + '.showInstanceData',
  SYNTAX_VIOLATION_EVENT: prefix + '.syntaxViolation',
  MAXINSTANCE_VIOLATION_EVENT: prefix + '.maxInstanceViolation',
  YES_PATTER_MATCHING_EVENT: prefix + '.yesPatternMatching',
  NO_PATTER_MATCHING_EVENT: prefix + '.noPatternMatching'
};
